name: Hello Testing
# This workflow is triggered on pushes to the repository v1.
on: [push]

jobs:
  build-and-run:
    name: Build and Run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build Code
        run: make
      - name: Nominal Run
        run: ./hello a b c d e f g h i j k l m n o p q r s t u v w x y z
      - uses: actions/upload-artifact@master
        with:
          name: hello-artifact
          path: hello

